---
- name: Update apt cache
  become: yes
  apt:
    update_cache: yes

- name: Upgrade all apt packages
  become: yes
  apt:
    name: '*'
    state: latest

- name: Clean up unused dependencies
  become: yes
  apt:
    autoremove: yes

- name: 'Install Node and NPM.'
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: Install PM2
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
