---
- name: Copy pm2 config
  copy:
    src: ecosystem.config.js
    dest: /home/ubuntu/ecosystem.config.js
    backup: yes

- name: Extract tarball
  become: yes
  unarchive:
    src: ~/project/backend.tar.gz
    dest: ~/
    list_files: yes
    mode: 0755

- name: Debug file path 1
  shell: ls

- name: Debug file path 2
  shell: ls ~/

- name: Debug env
  ansible.builtin.debug:
    msg:
      - "TYPEORM_HOST: {{ lookup('env', 'TYPEORM_HOST') }}"

- name: Debug file path 3
  shell: ls backend

- name: Execute Node application
  shell: pm2 startOrGracefulReload /home/ubuntu/ecosystem.config.js
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: /home/ubuntu/backend/src/modules/domain/**/*.entity.ts
    TYPEORM_MIGRATIONS_DIR: /home/ubuntu/backend/src/migrations
    TYPEORM_PORT: 5532
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
