---
- name: Copy pm2 config
  copy:
    src: ecosystem.config.js
    dest: ~/ecosystem.config.js
    backup: yes

- name: Copy application source
  copy:
    src: ~/project/backend/dist
    dest: ~/backend/dist
    backup: yes

- name: Debug...
  shell: pwd && ls && ls ./backend && ls ./backend/dist
  debugger: always

- name: Execute Node application
  shell: pm2 startOrGracefulReload ~/ecosystem.config.js
  debugger: on_failed
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ~/backend/dist/modules/domain/**/*.entity.js
    TYPEORM_PORT: 5532
    TYPEORM_HOST: lookup('env', 'TYPEORM_HOST')
    TYPEORM_USERNAME: lookup('env', 'TYPEORM_USERNAME')
    TYPEORM_PASSWORD: lookup('env', 'TYPEORM_PASSWORD')
    TYPEORM_DATABASE: lookup('env', 'TYPEORM_DATABASE')
