---
- name: Update packages
  become: yes
  apt:
    update_cache: yes

- name: Upgrade packages
  become: yes
  apt:
    name: ['*']
    state: latest

- name: Clean up unused dependencies
  become: yes
  apt:
    autoremove: yes
