version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: python:3.7-alpine3.11

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ['b2:4b:a1:40:4f:f6:ae:2f:5c:74:4d:18:94:16:b2:cf']
      - run: ansible-playbook main.yml -i inventory --verbose

workflows:
  ci_flow:
    jobs:
      - create_infrastructure
