version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ['d8:0b:0b:d1:13:d1:97:ac:8e:e7:99:09:96:0e:4b:24:4f:79:ad:48']
      - run:
          name: Install dependencies
          command: apk add --update ansible
      - run:
          name: Configure server
          command: ansible-playbook -i inventory.txt playbook.yml

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
