version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "Hello" >> /tmp/output.txt
      - persist_to_workspace:
          root: /tmp
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: /tmp
      - run: cat /tmp/output.txt

  do_pipeline_id_cmd:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id

workflows:
  use_workspaces:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
  do_command:
    jobs:
      - do_pipeline_id_cmd
