version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "Hello" >> output.txt
      - persist_to_workspace:
          root: /tmp
          paths:
            - ./

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: /tmp
      - run: cat /tmp/output.txt

workflows:
  use_workspaces:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
