---
- name: Download nvm installer
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v0.37.2/install.sh
    dest: /tmp/nvm-installer.sh
    mode: 0644
    backup: yes

- name: Execute the nvm installer
  command: /tmp/nvm-installer.sh
  args:
    creates: ~/.nvm/nvm.sh

- name: Update permissions for nvm activation script
  file:
    path: ~/.nvm/nvm.sh
    state: touch
    mode: 0644

- name: Activate nvm
  shell: /bin/bash ~/.nvm/nvm.sh

- name: Install NodeJS
  shell: |
    # ensures nvm is available before usage
    source ~/.bashrc
    nvm install --lts

- name: Install PM2
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
